In [1]:
# -*- coding: utf-8 -*-
"""Day-3_salesPrediction_LogisticRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xF0AZCONtjgJWZeamjEp-wP8UoUR4JTh

importing libraries
"""

import pandas as pd
import numpy as np


In [2]:
"""choose dataset file from local directory"""

from google.colab import files
upload = files.upload()

In [3]:
"""reading data into single variable 'dataset'"""

dataset = pd.read_csv('DigitalAd_dataset.csv')
print(dataset)


   age  salary  purchase
0   45   35000         1
1   18   10000         0
2   23   25000         1
3   35   37000         0
4   26   30000         1
5   22   35000         1
6   26   45000         1
7   55   60000         1
8   36   50000         1
9   31   20000         0


In [4]:
"""summarizing dataset"""

print(dataset.shape)
print(dataset.head(5))

(10, 3)
   age  salary  purchase
0   45   35000         1
1   18   10000         0
2   23   25000         1
3   35   37000         0
4   26   30000         1


In [5]:
"""segrigating data into input(i.e. x) and output (i.e. y)"""

x=dataset.iloc[:,:-1].values
x

y=dataset.iloc[:,-1].values
y

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [6]:
"""splitting the dataset into train and test"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [7]:
"""preprocessing data through feature scaling"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[-0.1765806 , -0.97059259],
       [-1.24783626, -1.63668555],
       [-0.58860201,  0.6946398 ],
       [ 1.80112216,  1.69377923],
       [ 0.15303652,  0.16176543],
       [ 0.97707934,  0.02854684],
       [-0.91821914,  0.02854684]])

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn import *
model = LogisticRegression()
model.fit(x_train, y_train)

age=int(input("Enter New Customer's age:"))
sal=int(input("Enter New Customer's salary:"))
newCust=[[age,sal]]
result=model.predict(sc.transform(newCust))
print(result)
if result==1:
  print("customer will buy")
else:
  print("customer will not buy")

y_pred=model.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)

print("confusion matrix:" )
print(cm)

print("accuracy of the model: {0}%".format(accuracy_score(y_test, y_pred)*100))

Enter New Customer's age:22
Enter New Customer's salary:45000
[1]
customer will buy
[[0 1]
 [1 1]
 [0 1]]
confusion matrix:
[[0 0]
 [2 1]]
accuracy of the model: 33.33333333333333%
